### ISSUE TITLE
Console scrolling doubles the last line

### ISSUE THREAD

**Issue by pixel-stuck** [b1l1s/ctr#1]
Not sure if it's because the last line isn't cleared (doesn't look like it because it persists up the image) or something else... thought it was a bug in my code, but then I realized, how can I be screwing printf up haha

**Comment by b1l1s** [comment]
A9LH with the same addresses for left/right framebuffers? It's probably caused by this
https://github.com/b1l1s/ctr/blob/master/src/draw.c#L205-L206 . Temp fix is to remove one of them.

**Comment by pixel-stuck** [comment]
@b1l1s : hmm, that makes sense, I'll try that, thanks

yup, that seems to have fixed it... thanks again
